sudo: false

language: r

warnings_are_errors: false

cache: packages

#before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

#os:
#  - osx

#install:
#  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'
#  - Rscript -e "devtools::install_github('jimhester/covr')"
 
r_packages:
  - covr

#script:
#  - Rscript -e 'devtools::check("ooc")'
  
r_github_packages:
  - codecov/example-r
#  - hadley/dplyr
#  - hadley/tidyr
#  - hadley/ggplot2
#  - ehrlinger/randomForestSRC

after_success:
#  - Rscript -e 'setwd("/Users/travis/build/tzuliu/")'
  #- bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
